### ISSUE TITLE
Leere Seite / Contao Einstellungen

### ISSUE THREAD

**Issue by thomashinze** [terhuerne/Contao-Aggregator#1]
Contao 3.3.6 / Aggregator 1.0.1 / URL Rewrite aktiviert
Nach der Installation der Erweiterung sieht man die BE Einstellungsseite vom Aggregator.
Bei Auswahl des Typen wird die Seite weiß. Es geht nicht weiter.

Die Contao Einstellungsseite ist bei installierter Erweiterung ebenfalls nicht mehr aufrufbar. 
Sie bleibt weiß. 

Debug Modus funktioniert leider nicht.

**Comment by chellerli** [comment]
Hi Johannes,
Hast du den Release bereits veröffentlicht? Ich habe das selbe Problem und konnte es übers Kleinschreiben des Ordners beheben.
Danke!
Gruss Marco

**Comment by terhuerne** [comment]
Hey @chellerli,

habe gerade noch einen neuen Release rausgegeben, jetzt sollte es auch wieder über das Extension Repository gehen.

Gruß,
Johannes

**Comment by terhuerne** [comment]
Hey @chellerli,

habe gerade noch einen neuen Release (Version 1.0.3) rausgegeben, jetzt sollte es auch wieder über das Extension Repository gehen.

Gruß,
Johannes
