### ISSUE TITLE
Only 10 items - Instagram Hashtag

### ISSUE THREAD

**Issue by kico** [terhuerne/Contao-Aggregator#10]
Hello,

I´ve installled Aggregator, set up instagram client ID and client Secret in the page settings. Than i´ve made Instagram Hashtag and inserted in one of the page. I had written that i wanted 99 photos and this is not working! 
If i write down only 1,2,9 or 4 photos than it´s working. Where should i look for the problem? 

thank you for your help!

**Comment by terhuerne** [comment]
Right now, it seems that the Instagram API is limited to just 10 Images per Search. I will have a look into this for the next release to eventually increase this limit.

**Comment by HumanDigital** [comment]
The Limitation of loaded posts (for twitter and instagram) can be found in modules/aggregator/classes/AggregatorEngine.php rows 347, 372, 389 and 400. Here it would be great, if the field value "numPosts" (table tl_content) would be used. 
Thank you very much for your great plugin!!!

![bildschirmfoto 2015-09-01 um 14 49 01](https://cloud.githubusercontent.com/assets/4395171/9604645/293b0cee-50b9-11e5-8816-740e504da398.png)

**Comment by terhuerne** [comment]
Fixed with Version 1.1. Should be available in the next minutes via composer.
