### ISSUE TITLE
Contao 3.5

### ISSUE THREAD

**Issue by uliverse** [terhuerne/Contao-Aggregator#12]
Hi,
I installed Aggregator on Contao 3.5 but it doesn't seem to work properly. When creating a feed I can't enter a Facebook alias; it just won't "stick" after saving...

**Comment by terhuerne** [comment]
Hey,
it seems that there is an issue with the facebook sdk. I will have a look into this this weekend and come back to you as soon as possible.

**Comment by msbt** [comment]
Is there an eta for version 2? I'm looking forward to set up a site with Facebook-Feed and as uliverse said, the alias keeps disappearing after saving it in 3.5.
Best regards!

**Comment by terhuerne** [comment]
Fixed with Version 1.1. Should be available in the next minutes via composer.
