### ISSUE TITLE
Instagram feed keeps disappearing 

### ISSUE THREAD

**Issue by memikeandi** [terhuerne/Contao-Aggregator#14]
Hi! Great extension! I´m having problem with the Instagram feed constantly disappearing and appearing agin, seemingly totally random. Thought it had something to do with the cashe-settings but the don´t relate. My Contao version is 3.5.2 so maybe there´s an issue there

Regards,

Mike

**Comment by terhuerne** [comment]
Hello Mike,

I'm going to release an API-Update this afternoon, as well as adding support for Contao 3.5.x.

**Comment by memikeandi** [comment]
Great news! (y)

**Comment by terhuerne** [comment]
Fixed with Version 1.1. Should be available in the next minutes via composer.
