### ISSUE TITLE
Facebook alias not accepted

### ISSUE THREAD

**Issue by rolandschuetz** [terhuerne/Contao-Aggregator#15]
I have created a Facebook App and added the app id and secret in the settings. Then I created a new aggregator source, selected type facebook and entered the alias "zentrum.fuer.citizen.science" for the facebook page https://www.facebook.com/zentrum.fuer.citizen.science/.

When pressing save the alias is cleared, there is not validation error message and no error in the logs.... what's wrong?

**Comment by terhuerne** [comment]
Hello @rolandschuetz,

this is an issue that refers to a change in the Facebook-API. I'm working on a fix which will be released approx. this afternoon.

**Comment by rolandschuetz** [comment]
AWESOME! :)

**Comment by terhuerne** [comment]
Fixed with Version 1.1. Should be available in the next minutes via composer.

**Comment by msbt** [comment]
Thanks for the update! Is the version in the composer different than the one from the package management? Because I updated the installation to 1.0.3.9005 but the alias still keeps disappearing in v3.5.4

**Comment by terhuerne** [comment]
Yes, because the new Version is 1.1.0. I've missed to publish the translations, so the updated Version has not appeared in the extension manager until now.

The update should be finally available in the next moments. If you still have problems with my extension, please let me know.

**Comment by msbt** [comment]
ok it is in the system now, but i get a blank page after upgrading on both, aggregator settings and contao settings :/

**Comment by terhuerne** [comment]
Can you please activate error messages temporarily and send me the error trace? Then I'll have a look.

**Comment by msbt** [comment]
Hallo Johannes,

der Fehler kommt, weil es nach dem Update auf einmal 2 aggregator dirs gibt, einmal capitalized und einmal lowercase, wenn man die files von /system/modules/Aggregator/ in /system/modules/aggregator/ verschiebt, funktioniert es einwandfrei. Irgendwo muss sich da ein Großbuchstaben eingeschlichen haben.

 

Was mir noch aufgefallen ist: In den Contao Settings gibt es jetzt 2mal den Punkt aggregator, kenne mich im Backend leider zu wenig aus, da könnte ich auch etwas versemmelt haben ;)

 

Lg und danke für das Update!

Matthias

 

Von: Johannes Terhürne [mailto:notifications@github.com] 
Gesendet: Samstag, 05. Dezember 2015 21:23
An: terhuerne/Contao-Aggregator
Cc: msbt
Betreff: Re: [Contao-Aggregator] Facebook alias not accepted (#15)

 

Can you please activate error messages temporarily and send me the error trace? Then I'll have a look.

**Comment by msbt** [comment]
ok I tried on a clean system, if you install it from scratch, it installs in /system/modules/Aggregator/, but it should be lowercase, if you rename it afterwards it works perfectly.

**Comment by terhuerne** [comment]
Sorry, I made a mistake while adding the files to the contao extension repository. The extension folder is now lowercase and should work now when updating. The current build-version is 5.

**Comment by msbt** [comment]
not to worry, very happy it is working now, really appreciate your efforts! thanks again

**Comment by rolandschuetz** [comment]
Now I was able to set the alias, but in Version 1.1.0 Build5 it results in the following error:
[06-Dec-2015 19:41:07 Europe/Vienna] 
PHP Warning: Invalid argument supplied for foreach() in /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/aggregator/elements/ContentAggregator.php on line 73
#0 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/aggregator/elements/ContentAggregator.php(73): __error(2, 'Invalid argumen...', '/home/.sites/13...', 73, Array)
#1 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/elements/ContentElement.php(260): Aggregator\ContentAggregator->compile()
#2 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/aggregator/elements/ContentAggregator.php(42): Contao\ContentElement->generate()
#3 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/library/Contao/Controller.php(476): Aggregator\ContentAggregator->generate()
#4 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#5 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#6 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#7 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#8 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), true, false, 'main')
#9 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#10 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/i18nl10n/pages/PageI18nl10nRegular.php(68): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#11 /home/.sites/135/site1067/web/zentrumfuercitizenscience/system/modules/core/controllers/FrontendIndex.php(267): Verstaerker\I18nl10n\Pages\PageI18nl10nRegular->generate(Object(Contao\PageModel), true)
#12 /home/.sites/135/site1067/web/zentrumfuercitizenscience/index.php(20): Contao\FrontendIndex->run()
#13 {main}

In the cache folder exists one empty file 1.json.cache

**Comment by terhuerne** [comment]
This happens if the Cronjob has not run once or no Data was return by the specific API. I've added a control-structure in Version 1.1.1 which does not throw that error, if no data is present, anymore.

**Comment by rolandschuetz** [comment]
Hello,

I'm currently using the poor many cronjob solution and it already only creates an empty file. Any ideas how to debug why there are no posts loaded from facebook?

Thanks,
Roland

**Comment by terhuerne** [comment]
Have you tried to call the cronjob directly from your browser (example.com/system/cron/cron.php)? Does it work now?

My experience is that the cronjob works best if you call it directly with a native cronjob of your server because of higher execution times.

**Comment by rolandschuetz** [comment]
I did call it from the browser and I added a echo "done" at the end to be sure that the cron executed properly.

**Comment by rolandschuetz** [comment]
Not sure why, but on my production server it works :)
