### ISSUE TITLE
Facebook timestamp ?

### ISSUE THREAD

**Issue by sfx12** [terhuerne/Contao-Aggregator#17]
Hallo !
Wie bekommt man es hin das Datum im deutschen Format anzeigen zu lassen, bei den posts von FB und z.b ohne Uhrzeit ?

ich habe es hier geändert: elements/ContentAggregator.php

$objTemplate->datetime = $objTemplate->datetime = date('Y-m-d\TH:i:sP', $arrItem['timestamp']);
....................................................
IN:
$objTemplate->datetime = $objTemplate->datetime = date('d-m-Y', $arrItem['timestamp']);

Aber es hat keinerlei Auswirkung, trotz cache leeren etc.

**Comment by terhuerne** [comment]
Hey,

der Wert $this->datetime ist nicht für die Freiformatierung vorgesehen. Dieser Wert ist für das Attribut datetime im HTML-Objekt <time> vorgesehen und dementsprechend nach ISO-Standard formatiert. 

Du kannst aber $this->date nutzen. Dann wird dir das Datum so formattiert, wie du es in den Contao-Einstellungen definiert hast.
