### ISSUE TITLE
Ausgabe eines Instagram Hashtags funktioniert nicht.

### ISSUE THREAD

**Issue by pretty-cool** [terhuerne/Contao-Aggregator#6]
Hi. Ich habe deine Erweiterung (1.0.3) in einer Contao Version 3.3.5 installiert. Die Ausgabe eines Instagram-Profils funktioniert auch schon mal. Aber wenn ich versuche einen Instagram Hashtag auszugeben, bekomme ich nichts angezeigt. Eine Idee woran dies liegen könnte?

**Comment by terhuerne** [comment]
Hey,
Kannst du bitte einen Screenshot von deiner Quellen-Definition hier posten? Dann schaue ich mir das gerne mal an. Eigentlich aggregiert das Plugin Instagram-Hashtags zuverlässig.

**Comment by pretty-cool** [comment]
Hi, vielen Dank für die schnelle Rückmeldung. Ich habe nun noch etwas mit der Erweiterung gespielt und mir ist noch etwas aufgefallen. Ich konnte inzwischen nach mehrmaligem hin und her auch einen Hashtag ausgeben. Allerdings scheinen mir gewisse Einstellungen irgendwie im Cache festzuhängen. Ich bin kein Programmierer aber versuche es mal zu umschreiben. Mir ist es zu erst bei dem Aggegator für den Twitter Hashtag augefallen. Ich hatte diesen angelegt und wollte danach den Begriff ändern, trotz Systemwartung und Reload blieb es jedoch in der Ausgabe beim vorherigen Motiv. Das gleiche Spiel bei Instagram. Und wenn ich dann einen Aggegator von Hashtag auf Profil umstelle, dann bleibt es ebenfall bei der Ansicht. So kam ich dann auch im ersten Moment zu einer leeren Ansicht.

Kannst du bei dir die Einträge besser überschreiben und aktualisieren? Muss ich ggf. noch in den Einstellungen etwas ändern?

**Comment by terhuerne** [comment]
Das System setzt aktuell auf ein eigenständiges, internes Caching um eine Rate-Limit-Sperre der Schnittstellen zu umgehen. Die Laufzeit des Caching definierst du beim anlegen/editieren einer Quelle.  Wird dort keine angegeben, wird eine Standardlaufzeit von 5 Minuten bei Instagram, 15 Minuten bei Twitter und 2 Minuten bei Facebook verwendet. Manuell kann der Cache aktuell noch nicht gelöscht werden, ist aber für einen zukünftigen Release geplant.

Bitte beachte darüber hinaus, dass du einen nativen Cron-Job für deine Contao Installation einrichtest. Der "Poor-Mans Cronjob" den Contao standardmäßig einsetzt, ist für das Modul zu unzuverlässig. Wie du native Cron-Jobs aktivierst, findest du hier: https://contao.org/de/cookbook/3.0/cronjobs-in-contao.html

**Comment by pretty-cool** [comment]
Alles klar, dann war ich einfach zu schnell beim Einrichten der Aggregatoren. Ich habe es eben noch einmal nach einer kurzen Pause versucht und es hat direkt funktioniert. Vielen Dank für den tollen Support und weiter so mit der Erweiterung - macht vom Aufbau und der Struktur einen sehr guten Eindruck.
