### ISSUE TITLE
Instagram Hashtag aggregieren funktioniert nicht mehr

### ISSUE THREAD

**Issue by uniqued** [terhuerne/Contao-Aggregator#8]
Gibt es eine Möglichkeit die Funktion des Aggregrators irgendwo zu loggen? Wir haben verschiedene Hastags auf unserer Seite implementiert, die auf einmal nicht mehr funktionieren. 

Es erscheint lediglich "Keine Beiträge vorhanden".

**Comment by terhuerne** [comment]
Fixed with Version 1.1. Should be available in the next minutes via composer.
