### ISSUE TITLE
Instagram Fehlermeldung "Zur Zeit sind keine Inhalte verfügbar."

### ISSUE THREAD

**Issue by konst1de** [terhuerne/Contao-Aggregator#9]
Habe mir einen API-Key geholt und den sowie das Secret ins Contao eingetragen. Jedoch kriege ich jedes mal diese oben genannte Fehlermeldung. Vor ein paar Wochen ging es noch Problemlos

**Comment by konst1de** [comment]
okay nun läuft es.. gibt es eine möglichkeit mehr als 20 Bilder zu erhalten?

**Comment by kico** [comment]
hast du eine möglichkeit für mehr bilder gefunden? ich kriege nur 10 Bilder :(

**Comment by terhuerne** [comment]
Fixed with Version 1.1. Should be available in the next minutes via composer.
